"use client";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import "./factory.css";

type LinkItem={id:string;provider:string;link_type:string;label:string;url:string;status:string;verified_at?:string|null};
type BusinessItem={business_key:string;business_name:string;relation_role:string};
type VersionItem={id:string;version_number:number;change_summary?:string|null;created_at:string};
type Product={id:string;name:string;slug:string;parent_id?:string|null;client_id?:string|null;product_type:string;description?:string|null;status:string;library_group?:string|null;library_role?:string|null;chatgpt_project_name?:string|null;chatgpt_link_status?:string|null;design_id?:string|null;design_status:string;current_version:number;approved_version?:number|null;approved_url?:string|null;internal_preview_url?:string|null;links:LinkItem[];businesses:BusinessItem[];asset_count:number;memory_count:number;history:VersionItem[]};
type View="preview"|"library"|"businesses"|"memory";
type Panel="ai"|"details"|"history";
const PROVIDERS=["chatgpt","drive","github","vercel","supabase","control_central","external"];
const QUICK=["Haz el diseño más premium sin cambiar el contenido","Mejora la experiencia móvil","Reduce ruido visual y mejora jerarquía","Haz el CTA principal más claro","Revisa accesibilidad y legibilidad"];

export default function FactoryClient(){
 const [products,setProducts]=useState<Product[]>([]),[activeId,setActiveId]=useState<string|null>(null),[view,setView]=useState<View>("preview"),[panel,setPanel]=useState<Panel>("ai");
 const [loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[modal,setModal]=useState<null|"product"|"link"|"business"|"memory">(null),[device,setDevice]=useState<"desktop"|"mobile">("desktop"),[reloadKey,setReloadKey]=useState(0),[aiConfigured,setAiConfigured]=useState(false),[aiBusy,setAiBusy]=useState(false),[prompt,setPrompt]=useState("");
 const previewRef=useRef<HTMLDivElement>(null);
 const active=useMemo(()=>products.find(p=>p.id===activeId)??products[0]??null,[products,activeId]);
 const verifiedVercel=active?.links.filter(l=>l.provider==="vercel"&&l.status==="verified")||[];
 const productionLink=verifiedVercel.find(l=>l.link_type.includes("production"))?.url||null;
 const approvedUrl=active?.approved_url||null;
 const businesses=useMemo(()=>{const map=new Map<string,BusinessItem>();products.flatMap(p=>p.businesses).forEach(b=>{if(!map.has(b.business_key))map.set(b.business_key,b)});return [...map.values()]},[products]);

 async function reload(keep=true){setLoading(true);try{const r=await fetch('/api/factory',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error);setProducts(j.products||[]);setAiConfigured(Boolean(j.ai?.configured));if((!keep||!activeId)&&j.products?.[0])setActiveId(j.products[0].id)}catch(e:any){setNotice(e.message)}finally{setLoading(false)}}
 useEffect(()=>{reload(false)},[]);
 async function post(payload:Record<string,unknown>){setNotice('');const r=await fetch('/api/factory',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok){setNotice(j.error||'Error');return false}await reload();return true}
 async function submitAI(text?:string){if(!active||aiBusy)return;const instruction=(text||prompt).trim();if(!instruction)return;setAiBusy(true);setNotice('');try{const r=await fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({product_id:active.id,instruction})}),j=await r.json();if(!r.ok)throw new Error(j.error||'No se pudo editar');setPrompt('');setNotice(`v${j.version} · ${j.summary}`);await reload();setReloadKey(k=>k+1)}catch(e:any){setNotice(e.message)}finally{setAiBusy(false)}}
 async function createProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post({action:'create_product',name:f.get('name'),product_type:f.get('type'),description:f.get('description')})){setModal(null);setView('preview');setPanel('ai')}}
 async function addLink(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget);if(await post({action:'add_link',product_id:active.id,provider:f.get('provider'),link_type:f.get('link_type'),label:f.get('label'),url:f.get('url')}))setModal(null)}
 async function addBusiness(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget);if(await post({action:'add_business',product_id:active.id,business_name:f.get('business_name'),relation_role:f.get('role')}))setModal(null)}
 async function addMemory(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget);if(await post({action:'add_memory',product_id:active.id,title:f.get('title'),memory_type:f.get('memory_type'),summary:f.get('summary'),source_url:f.get('source_url')}))setModal(null)}
 async function fullscreen(){if(!previewRef.current)return;document.fullscreenElement?await document.exitFullscreen():await previewRef.current.requestFullscreen()}

 return <div className="factory-shell">
  <aside className="factory-rail"><div className="factory-logo">LF</div>{([['preview','◫','Preview'],['library','⌗','Biblioteca'],['businesses','◉','Negocios'],['memory','⌘','Memoria']] as [View,string,string][]).map(([k,i,l])=><button key={k} className={view===k?'active':''} onClick={()=>setView(k)}><span>{i}</span><small>{l}</small></button>)}</aside>
  <main className="factory-main">
   <header className="factory-top"><div className="brand-lockup"><b>LINK Factory</b><span>Preview + AI Edit + Control Central</span></div><div className="top-actions">{active&&<span className="version-pill">v{active.current_version}</span>}<button onClick={()=>setModal('product')}>＋ Crear producto</button></div></header>
   {notice&&<div className="notice">{notice}</div>}
   <section className={`factory-page ${view==='preview'?'preview-page':''}`}>
   {loading?<div className="empty">Sincronizando con Control Central…</div>:products.length===0?<Empty onCreate={()=>setModal('product')}/>:<>
    {view==='preview'&&active&&<div className="studio">
      <div className="studio-head"><div><small>WORKING PRODUCT</small><select value={active.id} onChange={e=>{setActiveId(e.target.value);setReloadKey(k=>k+1)}}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="studio-actions"><button onClick={()=>setReloadKey(k=>k+1)}>↻</button><div className="device-control"><button className={device==='desktop'?'active':''} onClick={()=>setDevice('desktop')}>Desktop</button><button className={device==='mobile'?'active':''} onClick={()=>setDevice('mobile')}>Mobile</button></div><button onClick={fullscreen}>Presentar</button>{approvedUrl&&<button onClick={()=>window.open(approvedUrl,'_blank','noopener,noreferrer')}>Aprobada ↗</button>}{productionLink&&<button onClick={()=>window.open(productionLink,'_blank','noopener,noreferrer')}>Producción ↗</button>}<button className="approve" onClick={()=>post({action:'approve_version',product_id:active.id})}>Aprobar v{active.current_version}</button></div></div>
      <div className="studio-grid">
       <section className="preview-frame" ref={previewRef}><div className="browser-bar"><i/><i/><i/><div>/working/{active.slug} · v{active.current_version}</div></div><div className="preview-stage"><div className={`device-shell ${device}`}><iframe key={`${active.id}-${active.current_version}-${reloadKey}`} src={`/api/preview/${active.id}?v=${active.current_version}`} title={active.name} sandbox="allow-scripts allow-forms allow-modals allow-popups"/></div></div><footer><b>{active.name}</b><span>{active.approved_version?`aprobada v${active.approved_version} · `:''}{active.design_status} · HTML de trabajo en Control Central</span></footer></section>
       <aside className="side-panel">
        <nav><button className={panel==='ai'?'active':''} onClick={()=>setPanel('ai')}>AI Edit</button><button className={panel==='details'?'active':''} onClick={()=>setPanel('details')}>Ficha 360</button><button className={panel==='history'?'active':''} onClick={()=>setPanel('history')}>Versiones</button></nav>
        {panel==='ai'&&<div className="ai-panel"><div className="ai-status"><div><span className={`signal ${aiConfigured?'on':''}`}/><b>{aiConfigured?'LLM conectado':'LLM pendiente'}</b></div><small>{aiConfigured?'El servidor responderá desde Vercel.':'Configura OPEN_SOURCE_LLM_API_URL antes del deploy.'}</small></div><div className="ai-intro"><span>AI EDIT</span><h2>Conversa con<br/>el producto.</h2><p>La IA lee la ficha, negocios y memoria de Control Central. Cada cambio crea una versión nueva del HTML.</p></div><div className="quick-actions">{QUICK.map(q=><button key={q} disabled={!aiConfigured||aiBusy} onClick={()=>submitAI(q)}>{q}</button>)}</div><div className="composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')submitAI()}} placeholder="Ej: Mantén todo igual, pero haz el hero más editorial y mejora el CTA móvil…"/><button disabled={!aiConfigured||aiBusy||!prompt.trim()} onClick={()=>submitAI()}>{aiBusy?'Editando…':'Enviar ↗'}</button><small>⌘ Enter · Cada edición crea una versión reversible.</small></div></div>}
        {panel==='details'&&<div className="details-panel"><PanelSection title="Negocios" add={()=>setModal('business')}>{active.businesses.length?active.businesses.map(b=><Row key={b.business_key+b.relation_role} a={b.business_name} b={b.relation_role}/>):<p>Sin negocio asociado.</p>}</PanelSection><PanelSection title="Memoria" add={()=>setModal('memory')}><div className="metric"><strong>{active.memory_count}</strong><span>registros ligados</span></div></PanelSection><PanelSection title="Integraciones" add={()=>setModal('link')}>{active.links.length?active.links.map(l=><div className="link-row" key={l.id}><div><b>{l.label}</b><span>{l.provider} · {l.status}</span></div>{l.status==='verified'?<a href={l.url} target="_blank" rel="noreferrer">↗</a>:<button onClick={()=>post({action:'verify_link',link_id:l.id})}>Verificar</button>}</div>):<p>Sin links.</p>}</PanelSection></div>}
        {panel==='history'&&<div className="history-panel"><div className="history-head"><span>VERSIONADO</span><h2>Volver sin miedo.</h2><p>Cada edición IA conserva el HTML anterior en Control Central.</p></div>{active.history.map(v=><div className="history-row" key={v.id}><div><b>v{v.version_number}{active.approved_version===v.version_number?' · APROBADA':''}</b><span>{v.change_summary||'Sin resumen'}</span><small>{new Date(v.created_at).toLocaleString()}</small></div>{v.version_number!==active.current_version&&<button onClick={()=>post({action:'restore_version',product_id:active.id,version_number:v.version_number})}>Restaurar</button>}</div>)}</div>}
       </aside>
      </div>
     </div>}
    {view==='library'&&<div className="content-view"><Hero n="01" title="Biblioteca de productos" text="LINK Digital y sus proyectos viven aquí como productos versionados conectados con Control Central."/><div className="cards">{products.map(p=><button key={p.id} onClick={()=>{setActiveId(p.id);setView('preview')}}><span>{p.library_group||p.product_type}{p.library_role==='hub'?' · HUB':''}</span><h3>{p.name}</h3><p>{p.description||'Sin descripción.'}</p><footer><b>{p.approved_version?`Aprobada v${p.approved_version}`:`v${p.current_version}`}</b><small>{p.businesses.length} negocios · {p.memory_count} memorias{p.chatgpt_link_status==='pending_manual_link'?' · ChatGPT pendiente':''}</small></footer></button>)}</div></div>}
    {view==='businesses'&&<div className="content-view"><Hero n="02" title="Negocios conectados" text="Factory no duplica el negocio: relaciona cada producto con identidades de Control Central."/><div className="list">{businesses.length?businesses.map(b=><Row key={b.business_key} a={b.business_name} b={b.relation_role}/>):<p>Sin relaciones todavía.</p>}</div></div>}
    {view==='memory'&&<div className="content-view"><Hero n="03" title="Memoria central" text="La IA toma decisiones usando deep_memories y relaciones almacenadas en LINK CONTROL CENTRAL."/><div className="big-metric"><strong>{products.reduce((n,p)=>n+p.memory_count,0)}</strong><span>memorias ligadas a productos Factory</span></div></div>}
   </>}
   </section>
  </main>
  {modal==='product'&&<Modal title="Crear producto" close={()=>setModal(null)}><form onSubmit={createProduct}><label>Nombre<input name="name" required autoFocus/></label><label>Tipo<select name="type"><option value="website">Website</option><option value="landing">Landing</option><option value="catalog">Catálogo</option><option value="dashboard">Dashboard</option><option value="campaign">Campaña</option></select></label><label>Descripción<textarea name="description"/></label><button className="submit">Crear HTML de trabajo</button></form></Modal>}
  {modal==='link'&&<Modal title="Conectar integración" close={()=>setModal(null)}><form onSubmit={addLink}><label>Proveedor<select name="provider">{PROVIDERS.map(x=><option key={x}>{x}</option>)}</select></label><label>Tipo<input name="link_type" placeholder="preview / production / repository / folder" required/></label><label>Etiqueta<input name="label" required/></label><label>URL HTTPS<input name="url" type="url" required/></label><button className="submit">Guardar sin verificar</button></form></Modal>}
  {modal==='business'&&<Modal title="Asociar negocio" close={()=>setModal(null)}><form onSubmit={addBusiness}><label>Nombre del negocio<input name="business_name" required/></label><label>Relación<select name="role"><option value="belongs_to">Pertenece a</option><option value="serves">Sirve a</option><option value="campaign_for">Campaña para</option></select></label><button className="submit">Relacionar en Control Central</button></form></Modal>}
  {modal==='memory'&&<Modal title="Agregar memoria" close={()=>setModal(null)}><form onSubmit={addMemory}><label>Título<input name="title" required/></label><label>Tipo<select name="memory_type"><option value="decision">Decisión</option><option value="context">Contexto</option><option value="instruction">Regla</option><option value="reference">Referencia</option></select></label><label>Contenido<textarea name="summary" required/></label><label>Fuente opcional<input name="source_url" type="url"/></label><button className="submit">Guardar memoria</button></form></Modal>}
 </div>
}
function Empty({onCreate}:{onCreate:()=>void}){return <div className="empty-state"><span>NO HAY DATOS FAKE</span><h1>Crea el primer<br/>producto real.</h1><p>Factory generará un HTML de trabajo versionado en Supabase Control Central.</p><button onClick={onCreate}>Crear producto</button></div>}
function Hero({n,title,text}:{n:string;title:string;text:string}){return <header className="hero"><span>{n}</span><div><h1>{title}</h1><p>{text}</p></div></header>}
function PanelSection({title,add,children}:{title:string;add:()=>void;children:React.ReactNode}){return <section className="panel-section"><header><b>{title}</b><button onClick={add}>＋</button></header>{children}</section>}
function Row({a,b}:{a:string;b:string}){return <div className="row"><b>{a}</b><span>{b}</span></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><div className="modal"><header><h3>{title}</h3><button onClick={close}>×</button></header>{children}</div></div>}
