"use client";
import { FormEvent, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { BUILTIN_SKILLS, BUILTIN_STYLES, type FactoryCapability } from "@/lib/factory-capabilities";
import "./factory-v2.css";

type LinkItem={id:string;provider:string;link_type:string;label:string;url:string;status:string;verified_at?:string|null};
type BusinessItem={business_key:string;business_name:string;relation_role:string};
type GenerationMeta={instruction?:string;request_summary?:string;compiled_prompt?:string;model?:string;provider?:string;temperature?:number;generated_at?:string;generation_id?:string|null;usage?:any;skills?:string[];style?:string|null;references?:any[]};
type VersionItem={id:string;version_number:number;change_summary?:string|null;created_at:string;metadata?:GenerationMeta|null};
type Product={id:string;name:string;slug:string;product_type:string;description?:string|null;status:string;design_id?:string|null;design_status:string;current_version:number;approved_version?:number|null;approved_url?:string|null;links:LinkItem[];businesses:BusinessItem[];asset_count:number;memory_count:number;history:VersionItem[];library_group?:string|null;library_role?:string|null;chatgpt_link_status?:string|null};
type Reference={id:string;label:string;url:string;role:string;notes?:string};
type Config={active_skills:string[];active_style:string|null;references:Reference[];custom_rules:string[];notify:boolean;sound:boolean};
type View="preview"|"library"|"businesses"|"memory";
type Panel="ai"|"setup"|"details"|"history";
type FullPanel=""|"ai"|"skills"|"style"|"refs"|"prompt"|"versions"|"code";
type ModalName=null|"product"|"link"|"business"|"memory"|"capability"|"reference"|"rule";
const PROVIDERS=["chatgpt","drive","github","vercel","supabase","control_central","external"];
const QUICK=["Haz el diseño más premium sin cambiar el contenido","Mejora la experiencia móvil","Reduce ruido visual y mejora jerarquía","Haz el CTA principal más claro","Revisa accesibilidad y legibilidad"];
const DEFAULT_CONFIG:Config={active_skills:["mobile-first","accessibility"],active_style:"link-minimal",references:[],custom_rules:[],notify:true,sound:true};

function firstGeneration(p:Product|null){return p?[...p.history].sort((a,b)=>a.version_number-b.version_number).find(v=>v.metadata?.instruction)||null:null}
function latestGeneration(p:Product|null){return p?.history.find(v=>v.metadata?.instruction)||null}
function productBrief(p:Product){const v=firstGeneration(p);return v?.metadata?.request_summary||v?.change_summary||p.description||"Sin prompt registrado todavía."}
function fmt(v?:string|null){if(!v)return"—";try{return new Date(v).toLocaleString()}catch{return v}}
function skillName(id:string,all:FactoryCapability[]){return all.find(x=>x.id===id)?.name||id}

export default function FactoryClientV2(){
 const [products,setProducts]=useState<Product[]>([]),[activeId,setActiveId]=useState<string|null>(null),[view,setView]=useState<View>("preview"),[panel,setPanel]=useState<Panel>("ai");
 const [loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[modal,setModal]=useState<ModalName>(null),[device,setDevice]=useState<"desktop"|"mobile">("desktop"),[reloadKey,setReloadKey]=useState(0);
 const [aiConfigured,setAiConfigured]=useState(false),[buildBusy,setBuildBusy]=useState(false),[prompt,setPrompt]=useState(""),[progress,setProgress]=useState<{pct:number;stage:string;estimated?:boolean}|null>(null);
 const [config,setConfig]=useState<Config>(DEFAULT_CONFIG),[customCaps,setCustomCaps]=useState<FactoryCapability[]>([]),[compiledPrompt,setCompiledPrompt]=useState(""),[code,setCode]=useState("");
 const [isFullscreen,setIsFullscreen]=useState(false),[fullPanel,setFullPanel]=useState<FullPanel>(""),[compare,setCompare]=useState(false);
 const previewRef=useRef<HTMLElement>(null);
 const active=useMemo(()=>products.find(p=>p.id===activeId)??products[0]??null,[products,activeId]);
 const allCaps=useMemo(()=>[...BUILTIN_SKILLS,...BUILTIN_STYLES,...customCaps],[customCaps]);
 const activeStyle=allCaps.find(x=>x.id===config.active_style&&x.kind==="style")||null;
 const originalGeneration=useMemo(()=>firstGeneration(active),[active]);
 const recentGeneration=useMemo(()=>latestGeneration(active),[active]);
 const verifiedVercel=active?.links.filter(l=>l.provider==="vercel"&&l.status==="verified")||[];
 const productionLink=verifiedVercel.find(l=>l.link_type.includes("production"))?.url||null;
 const businesses=useMemo(()=>{const map=new Map<string,BusinessItem>();products.flatMap(p=>p.businesses||[]).forEach(b=>{if(!map.has(b.business_key))map.set(b.business_key,b)});return [...map.values()]},[products]);

 async function reload(keep=true){setLoading(true);try{const r=await fetch("/api/factory",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error);setProducts(j.products||[]);setAiConfigured(Boolean(j.ai?.configured));if((!keep||!activeId)&&j.products?.[0])setActiveId(j.products[0].id)}catch(e:any){setNotice(e.message)}finally{setLoading(false)}}
 async function loadCaps(){try{const r=await fetch("/api/capabilities",{cache:"no-store"}),j=await r.json();setCustomCaps(j.custom||[])}catch{}}
 async function loadConfig(id:string){try{const r=await fetch(`/api/factory-config?product_id=${encodeURIComponent(id)}`,{cache:"no-store"}),j=await r.json();if(r.ok)setConfig({...DEFAULT_CONFIG,...j.config})}catch{setConfig(DEFAULT_CONFIG)}}
 useEffect(()=>{reload(false);loadCaps()},[]);
 useEffect(()=>{if(active?.id)loadConfig(active.id)},[active?.id]);
 useEffect(()=>{const h=()=>{const on=Boolean(document.fullscreenElement);setIsFullscreen(on);if(!on){setFullPanel("");setCompare(false)}};document.addEventListener("fullscreenchange",h);return()=>document.removeEventListener("fullscreenchange",h)},[]);

 async function post(payload:Record<string,unknown>){setNotice("");const r=await fetch("/api/factory",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok){setNotice(j.error||"Error");return false}await reload();return true}
 async function persistConfig(next:Config){if(!active)return;setConfig(next);const r=await fetch("/api/factory-config",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({product_id:active.id,config:next})});if(!r.ok){const j=await r.json().catch(()=>({}));setNotice(j.error||"No se guardó la configuración")}}
 function toggleSkill(id:string){const has=config.active_skills.includes(id);persistConfig({...config,active_skills:has?config.active_skills.filter(x=>x!==id):[...config.active_skills,id]})}
 function setStyle(id:string|null){persistConfig({...config,active_style:id})}
 function beep(){try{const C=(window.AudioContext||(window as any).webkitAudioContext);const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=740;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.08,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.22);o.start();o.stop(c.currentTime+.24)}catch{}}
 function finishNotify(summary:string){if(config.sound)beep();document.title=`✓ ${active?.name||"LINK Factory"} · listo`;setTimeout(()=>{document.title="LINK Factory"},12000);if(config.notify&&"Notification"in window&&Notification.permission==="granted")new Notification("LINK Factory · construcción lista",{body:summary})}
 async function prepareNotification(){if(config.notify&&"Notification"in window&&Notification.permission==="default")try{await Notification.requestPermission()}catch{}}

 async function submitBuild(text?:string){if(!active||buildBusy)return;const instruction=(text||prompt).trim();if(!instruction)return;await prepareNotification();setBuildBusy(true);setNotice("");setProgress({pct:3,stage:"Iniciando"});let simulated:any=null;
  try{
   const r=await fetch("/api/build",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({product_id:active.id,instruction})});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||"No se pudo generar")}
   const reader=r.body?.getReader();if(!reader)throw new Error("El navegador no pudo abrir el stream de generación");const dec=new TextDecoder();let buffer="";
   simulated=setInterval(()=>setProgress(p=>p&&p.pct>=40&&p.pct<78?{...p,pct:Math.min(78,p.pct+1),estimated:true}:p),1100);
   while(true){const {done,value}=await reader.read();if(done)break;buffer+=dec.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line.trim())continue;const ev=JSON.parse(line);if(ev.type==="progress"||ev.type==="compiled")setProgress({pct:ev.pct||0,stage:ev.stage||"Generando",estimated:ev.estimated});if(ev.compiled_prompt)setCompiledPrompt(ev.compiled_prompt);if(ev.type==="error")throw new Error(ev.message);if(ev.type==="done"){setProgress({pct:100,stage:"Construcción lista"});setPrompt("");setNotice(`v${ev.version} · ${ev.summary}`);finishNotify(ev.summary);await reload();setReloadKey(k=>k+1);setTimeout(()=>setProgress(null),4500)}}}
  }catch(e:any){setProgress(null);setNotice(e.message||"Error de generación")}finally{if(simulated)clearInterval(simulated);setBuildBusy(false)}
 }
 async function compiled(){if(!active)return;const r=await fetch(`/api/build?product_id=${encodeURIComponent(active.id)}&instruction=${encodeURIComponent(prompt||"Sin nueva instrucción")}`,{cache:"no-store"}),j=await r.json();if(r.ok)setCompiledPrompt(j.compiled_prompt||"");else setNotice(j.error||"No se pudo compilar")}
 async function loadCode(){if(!active)return;const r=await fetch(`/api/preview/${active.id}?v=${active.current_version}`,{cache:"no-store"});setCode(await r.text())}
 async function fullscreen(){if(!previewRef.current)return;if(document.fullscreenElement)await document.exitFullscreen();else await previewRef.current.requestFullscreen()}
 async function createProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post({action:"create_product",name:f.get("name"),product_type:f.get("type"),description:f.get("description")})){setModal(null);setView("preview");setPanel("ai")}}
 async function addLink(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget);if(await post({action:"add_link",product_id:active.id,provider:f.get("provider"),link_type:f.get("link_type"),label:f.get("label"),url:f.get("url")}))setModal(null)}
 async function addBusiness(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget);if(await post({action:"add_business",product_id:active.id,business_name:f.get("business_name"),relation_role:f.get("role")}))setModal(null)}
 async function addMemory(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget);if(await post({action:"add_memory",product_id:active.id,title:f.get("title"),memory_type:f.get("memory_type"),summary:f.get("summary"),source_url:f.get("source_url")}))setModal(null)}
 async function addCapability(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),kind=String(f.get("kind")||"skill");const r=await fetch("/api/capabilities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,name:f.get("name"),description:f.get("description"),instructions:f.get("instructions")})}),j=await r.json();if(!r.ok){setNotice(j.error||"No se guardó");return}await loadCaps();if(kind==="skill")await persistConfig({...config,active_skills:[...config.active_skills,j.capability.id]});else await persistConfig({...config,active_style:j.capability.id});setModal(null)}
 async function addReference(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const ref:Reference={id:crypto.randomUUID(),label:String(f.get("label")||"Referencia"),url:String(f.get("url")||""),role:String(f.get("role")||"inspiration"),notes:String(f.get("notes")||"")};await persistConfig({...config,references:[...config.references,ref]});setModal(null)}
 async function addRule(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),rule=String(f.get("rule")||"").trim();if(rule)await persistConfig({...config,custom_rules:[...config.custom_rules,rule]});setModal(null)}

 return <div className="factory-shell-v2">
  <aside className="factory-rail-v2"><div className="factory-logo"/>{([['preview','◫','Preview'],['library','⌗','Biblioteca'],['businesses','◉','Negocios'],['memory','⌘','Memoria']] as [View,string,string][]).map(([k,i,l])=><button key={k} className={view===k?"active":""} onClick={()=>setView(k)}><span>{i}</span><small>{l}</small></button>)}</aside>
  <main className="factory-main-v2">
   <header className="factory-top-v2"><div className="brand-lockup"><b>LINK Factory</b><span>Build Engine + Control Central</span></div><div className="top-actions">{active&&<span className="version-pill">v{active.current_version}</span>}<button onClick={()=>setModal("product")}>＋ Crear producto</button></div></header>
   {notice&&<div className="notice-v2">{notice}</div>}
   <section className={`factory-page-v2 ${view==="preview"?"preview-page-v2":""}`}>
    {loading?<div className="empty-v2">Sincronizando con Control Central…</div>:products.length===0?<Empty onCreate={()=>setModal("product")}/>:<>
    {view==="preview"&&active&&<div className="studio-v2">
      <div className="studio-head-v2"><div><small>WORKING PRODUCT</small><select value={active.id} onChange={e=>{setActiveId(e.target.value);setReloadKey(k=>k+1)}}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="studio-actions"><button onClick={()=>setReloadKey(k=>k+1)}>↻</button><div className="device-control"><button className={device==="desktop"?"active":""} onClick={()=>setDevice("desktop")}>Desktop</button><button className={device==="mobile"?"active":""} onClick={()=>setDevice("mobile")}>Mobile</button></div><button onClick={fullscreen}>{isFullscreen?"Salir":"Build Mode"}</button>{active.approved_url&&<button onClick={()=>window.open(active.approved_url,"_blank")}>Aprobada ↗</button>}{productionLink&&<button onClick={()=>window.open(productionLink,"_blank")}>Producción ↗</button>}<button className="approve" onClick={()=>post({action:"approve_version",product_id:active.id})}>Aprobar v{active.current_version}</button></div></div>
      <div className="studio-grid-v2">
       <section className={`preview-frame-v2 ${isFullscreen?"is-fullscreen":""}`} ref={previewRef}>
        <div className="browser-bar-v2"><i/><i/><i/><div>/working/{active.slug} · v{active.current_version}</div></div>
        {progress&&<div className={`build-progress ${progress.pct===100?"done":""}`}><div><b>{progress.pct}%</b><span>{progress.stage}{progress.estimated?" · estimado":""}</span></div><div className="progress-track"><span style={{width:`${progress.pct}%`}}/></div></div>}
        <div className={`preview-stage-v2 ${compare?"compare":""}`}>
         {compare&&active.current_version>1?<><div className="compare-pane"><label>ANTES · v{active.current_version-1}</label><iframe src={`/api/preview/${active.id}?v=${active.current_version-1}`} title="Versión anterior"/></div><div className="compare-pane"><label>AHORA · v{active.current_version}</label><iframe key={`c-${reloadKey}`} src={`/api/preview/${active.id}?v=${active.current_version}`} title="Versión actual"/></div></>:<div className={`device-shell-v2 ${device}`}><iframe key={`${active.id}-${active.current_version}-${reloadKey}`} src={`/api/preview/${active.id}?v=${active.current_version}`} title={active.name} sandbox="allow-scripts allow-forms allow-modals allow-popups"/></div>}
        </div>
        <footer className="preview-footer-v2"><b>{active.name}</b><span>{active.design_status} · Control Central</span></footer>
        <div className="fullscreen-dock">
         <button className={fullPanel==="ai"?"active":""} onClick={()=>setFullPanel(fullPanel==="ai"?"":"ai")}>AI Edit</button>
         <button className={fullPanel==="skills"?"active":""} onClick={()=>setFullPanel(fullPanel==="skills"?"":"skills")}>Skills {config.active_skills.length}</button>
         <button className={fullPanel==="style"?"active":""} onClick={()=>setFullPanel(fullPanel==="style"?"":"style")}>Estilo</button>
         <button className={fullPanel==="refs"?"active":""} onClick={()=>setFullPanel(fullPanel==="refs"?"":"refs")}>Refs {config.references.length}</button>
         <button onClick={()=>{setCompare(!compare);setFullPanel("")}} className={compare?"active":""}>Comparar</button>
         <button onClick={()=>setDevice(device==="desktop"?"mobile":"desktop")}>{device==="desktop"?"Mobile":"Desktop"}</button>
         <button onClick={()=>{compiled();setFullPanel("prompt")}}>Prompt</button>
         <button onClick={()=>{loadCode();setFullPanel("code")}}>Código</button>
         <button onClick={()=>setFullPanel("versions")}>v{active.current_version}</button>
         <button onClick={fullscreen}>Salir</button>
        </div>
        {isFullscreen&&fullPanel&&<div className="build-drawer"><header><div><small>LINK FACTORY BUILD MODE</small><b>{drawerTitle(fullPanel)}</b></div><button onClick={()=>setFullPanel("")}>×</button></header><div className="drawer-body">{fullPanel==="ai"&&<AIComposer prompt={prompt} setPrompt={setPrompt} busy={buildBusy} progress={progress} submit={submitBuild}/>} {fullPanel==="skills"&&<Skills all={allCaps.filter(x=>x.kind==="skill")} config={config} toggle={toggleSkill} add={()=>setModal("capability")}/>} {fullPanel==="style"&&<Styles all={allCaps.filter(x=>x.kind==="style")} active={config.active_style} setStyle={setStyle} add={()=>setModal("capability")}/>} {fullPanel==="refs"&&<References refs={config.references} add={()=>setModal("reference")} remove={id=>persistConfig({...config,references:config.references.filter(r=>r.id!==id)})}/>} {fullPanel==="prompt"&&<PromptView value={compiledPrompt}/>} {fullPanel==="versions"&&<Versions product={active} post={post}/>} {fullPanel==="code"&&<CodeView value={code}/>}</div></div>}
       </section>
       <aside className="side-panel-v2"><nav><button className={panel==="ai"?"active":""} onClick={()=>setPanel("ai")}>AI Edit</button><button className={panel==="setup"?"active":""} onClick={()=>setPanel("setup")}>Build Setup</button><button className={panel==="details"?"active":""} onClick={()=>setPanel("details")}>Ficha</button><button className={panel==="history"?"active":""} onClick={()=>setPanel("history")}>Versiones</button></nav>
        {panel==="ai"&&<div className="side-scroll"><div className="ai-status"><div><span className={`signal ${aiConfigured?"on":""}`}/><b>{aiConfigured?"LLM conectado":"LLM pendiente"}</b></div><small>{aiConfigured?`${config.active_skills.length} skills · ${activeStyle?.name||"sin estilo"} · ${config.references.length} referencias`:"Configura OPEN_SOURCE_LLM_API_URL"}</small></div><div className="ai-intro"><span>AI BUILD</span><h2>Conversa con<br/>la construcción.</h2><p>El motor compila reglas + habilidades + estilo + referencias + memoria antes de generar.</p></div><div className="quick-actions">{QUICK.map(q=><button key={q} disabled={!aiConfigured||buildBusy} onClick={()=>submitBuild(q)}>{q}</button>)}</div><AIComposer prompt={prompt} setPrompt={setPrompt} busy={buildBusy} progress={progress} submit={submitBuild}/></div>}
        {panel==="setup"&&<div className="side-scroll"><SetupSummary config={config} style={activeStyle} all={allCaps} addRule={()=>setModal("rule")} toggleNotify={k=>persistConfig({...config,[k]:!config[k]})}/><Skills all={allCaps.filter(x=>x.kind==="skill")} config={config} toggle={toggleSkill} add={()=>setModal("capability")}/><Styles all={allCaps.filter(x=>x.kind==="style")} active={config.active_style} setStyle={setStyle} add={()=>setModal("capability")}/><References refs={config.references} add={()=>setModal("reference")} remove={id=>persistConfig({...config,references:config.references.filter(r=>r.id!==id)})}/><Rules rules={config.custom_rules} add={()=>setModal("rule")} remove={i=>persistConfig({...config,custom_rules:config.custom_rules.filter((_,n)=>n!==i)})}/></div>}
        {panel==="details"&&<div className="side-scroll"><GenerationSheet product={active} original={originalGeneration} latest={recentGeneration} all={allCaps}/><PanelSection title="Negocios" add={()=>setModal("business")}>{active.businesses.length?active.businesses.map(b=><Row key={b.business_key+b.relation_role} a={b.business_name} b={b.relation_role}/>):<p>Sin negocio asociado.</p>}</PanelSection><PanelSection title="Memoria" add={()=>setModal("memory")}><div className="metric"><strong>{active.memory_count}</strong><span>registros ligados</span></div></PanelSection><PanelSection title="Integraciones" add={()=>setModal("link")}>{active.links.length?active.links.map(l=><div className="link-row" key={l.id}><div><b>{l.label}</b><span>{l.provider} · {l.status}</span></div>{l.status==="verified"?<a href={l.url} target="_blank" rel="noreferrer">↗</a>:<button onClick={()=>post({action:"verify_link",link_id:l.id})}>Verificar</button>}</div>):<p>Sin links.</p>}</PanelSection></div>}
        {panel==="history"&&<div className="side-scroll"><Versions product={active} post={post}/></div>}
       </aside>
      </div>
     </div>}
    {view==="library"&&<div className="content-view-v2"><Hero n="01" title="Biblioteca de construcciones" text="Cada producto conserva solicitud, habilidades, referencias, prompt compilado, versiones y datos de generación."/><div className="cards-v2">{products.map(p=><button key={p.id} onClick={()=>{setActiveId(p.id);setView("preview");setPanel("details")}}><span>{p.library_group||p.product_type}</span><h3>{p.name}</h3><p>{productBrief(p)}</p><footer><b>{p.approved_version?`Aprobada v${p.approved_version}`:`v${p.current_version}`}</b><small>{p.businesses.length} negocios · {p.memory_count} memorias</small></footer></button>)}</div></div>}
    {view==="businesses"&&<div className="content-view-v2"><Hero n="02" title="Negocios conectados" text="Los productos se relacionan con negocios reales de Control Central."/><div className="list-v2">{businesses.length?businesses.map(b=><Row key={b.business_key} a={b.business_name} b={b.relation_role}/>):<p>Sin relaciones todavía.</p>}</div></div>}
    {view==="memory"&&<div className="content-view-v2"><Hero n="03" title="Memoria central" text="La construcción incorpora memorias relevantes antes de llamar al modelo."/><div className="big-metric"><strong>{products.reduce((n,p)=>n+p.memory_count,0)}</strong><span>memorias ligadas</span></div></div>}
    </>}
   </section>
  </main>
  {modal==="product"&&<Modal title="Crear producto" close={()=>setModal(null)}><form onSubmit={createProduct}><label>Nombre<input name="name" required autoFocus/></label><label>Tipo<select name="type"><option value="website">Website</option><option value="landing">Landing</option><option value="catalog">Catálogo</option><option value="dashboard">Dashboard</option><option value="campaign">Campaña</option></select></label><label>Contexto inicial<textarea name="description"/></label><button className="submit-v2">Crear construcción</button></form></Modal>}
  {modal==="link"&&<Modal title="Conectar integración" close={()=>setModal(null)}><form onSubmit={addLink}><label>Proveedor<select name="provider">{PROVIDERS.map(x=><option key={x}>{x}</option>)}</select></label><label>Tipo<input name="link_type" required/></label><label>Etiqueta<input name="label" required/></label><label>URL HTTPS<input name="url" type="url" required/></label><button className="submit-v2">Guardar</button></form></Modal>}
  {modal==="business"&&<Modal title="Asociar negocio" close={()=>setModal(null)}><form onSubmit={addBusiness}><label>Negocio<input name="business_name" required/></label><label>Relación<select name="role"><option value="belongs_to">Pertenece a</option><option value="serves">Sirve a</option><option value="campaign_for">Campaña para</option></select></label><button className="submit-v2">Relacionar</button></form></Modal>}
  {modal==="memory"&&<Modal title="Agregar memoria" close={()=>setModal(null)}><form onSubmit={addMemory}><label>Título<input name="title" required/></label><label>Tipo<select name="memory_type"><option value="decision">Decisión</option><option value="context">Contexto</option><option value="instruction">Regla</option><option value="reference">Referencia</option></select></label><label>Contenido<textarea name="summary" required/></label><label>Fuente<input name="source_url" type="url"/></label><button className="submit-v2">Guardar memoria</button></form></Modal>}
  {modal==="capability"&&<Modal title="Nueva habilidad / estilo" close={()=>setModal(null)}><form onSubmit={addCapability}><label>Tipo<select name="kind"><option value="skill">Habilidad</option><option value="style">Style Pack</option></select></label><label>Nombre<input name="name" required/></label><label>Descripción<input name="description"/></label><label>Instrucciones<textarea name="instructions" required placeholder={'Una regla por línea.\nEj: El CTA principal siempre debe aparecer sobre el fold.'}/></label><button className="submit-v2">Guardar en biblioteca</button></form></Modal>}
  {modal==="reference"&&<Modal title="Agregar referencia" close={()=>setModal(null)}><form onSubmit={addReference}><label>Nombre<input name="label" required/></label><label>URL HTTPS<input name="url" type="url" required/></label><label>Usar para<select name="role"><option value="inspiration">Inspiración general</option><option value="layout">Layout</option><option value="style">Estilo visual</option><option value="ux">UX</option><option value="content">Contenido</option><option value="motion">Motion</option></select></label><label>Qué debe tomar de esta referencia<textarea name="notes" placeholder="Ej: tomar ritmo editorial y navegación, no copiar colores ni textos."/></label><button className="submit-v2">Agregar referencia</button></form></Modal>}
  {modal==="rule"&&<Modal title="Regla de esta construcción" close={()=>setModal(null)}><form onSubmit={addRule}><label>Regla<textarea name="rule" required placeholder="Ej: Nunca mostrar precios sin IVA."/></label><button className="submit-v2">Agregar regla</button></form></Modal>}
 </div>
}

function drawerTitle(p:FullPanel){return({ai:"AI Edit",skills:"Habilidades",style:"Estilo",refs:"Referencias",prompt:"Prompt compilado",versions:"Versiones",code:"Código"} as any)[p]||"Build Mode"}
function AIComposer({prompt,setPrompt,busy,progress,submit}:{prompt:string;setPrompt:(v:string)=>void;busy:boolean;progress:any;submit:(v?:string)=>void}){return <div className="composer-v2"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==="Enter")submit()}} placeholder="Describe exactamente qué quieres construir o modificar…"/><button disabled={busy||!prompt.trim()} onClick={()=>submit()}>{busy?`${progress?.pct||0}% · ${progress?.stage||"Generando"}`:"Generar ↗"}</button><small>⌘ Enter · cada generación crea una versión reversible.</small></div>}
function Skills({all,config,toggle,add}:{all:FactoryCapability[];config:Config;toggle:(id:string)=>void;add:()=>void}){return <section className="config-section"><header><div><b>Habilidades</b><small>{config.active_skills.length} activas</small></div><button onClick={add}>＋ Nueva</button></header><div className="cap-grid">{all.map(s=><button key={s.id} className={config.active_skills.includes(s.id)?"selected":""} onClick={()=>toggle(s.id)}><b>{s.name}</b><span>{s.description}</span><small>{config.active_skills.includes(s.id)?"✓ Activa":"Activar"}{!s.builtin?" · Personalizada":""}</small></button>)}</div></section>}
function Styles({all,active,setStyle,add}:{all:FactoryCapability[];active:string|null;setStyle:(id:string|null)=>void;add:()=>void}){return <section className="config-section"><header><div><b>Style Pack</b><small>Dirección visual</small></div><button onClick={add}>＋ Nuevo</button></header><div className="style-list"><button className={!active?"selected":""} onClick={()=>setStyle(null)}>Sin estilo</button>{all.map(s=><button key={s.id} className={active===s.id?"selected":""} onClick={()=>setStyle(s.id)}><b>{s.name}</b><span>{s.description}</span></button>)}</div></section>}
function References({refs,add,remove}:{refs:Reference[];add:()=>void;remove:(id:string)=>void}){return <section className="config-section"><header><div><b>Referencias</b><small>{refs.length} conectadas</small></div><button onClick={add}>＋ Agregar</button></header>{refs.length?refs.map(r=><div className="reference-row" key={r.id}><div><b>{r.label}</b><span>{r.role} · {r.notes||"sin notas"}</span><a href={r.url} target="_blank" rel="noreferrer">{r.url}</a></div><button onClick={()=>remove(r.id)}>×</button></div>):<p className="muted">Agrega websites o URLs y explica qué debe aprender de cada una.</p>}</section>}
function Rules({rules,add,remove}:{rules:string[];add:()=>void;remove:(i:number)=>void}){return <section className="config-section"><header><div><b>Reglas propias</b><small>Se suman a las reglas LINK</small></div><button onClick={add}>＋ Regla</button></header>{rules.map((r,i)=><div className="rule-row" key={i}><span>{r}</span><button onClick={()=>remove(i)}>×</button></div>)}{!rules.length&&<p className="muted">Sin reglas adicionales.</p>}</section>}
function SetupSummary({config,style,all,addRule,toggleNotify}:{config:Config;style:FactoryCapability|null;all:FactoryCapability[];addRule:()=>void;toggleNotify:(k:"notify"|"sound")=>void}){return <div className="setup-summary"><span>BUILD CONTEXT</span><h2>Cómo va a pensar<br/>Factory.</h2><div className="setup-metrics"><div><b>{config.active_skills.length}</b><small>skills</small></div><div><b>{config.references.length}</b><small>refs</small></div><div><b>{config.custom_rules.length}</b><small>reglas</small></div></div><p><b>Estilo:</b> {style?.name||"Sin style pack"}</p><p><b>Skills:</b> {config.active_skills.map(id=>skillName(id,all)).join(", ")||"ninguna"}</p><div className="toggle-row"><button className={config.notify?"on":""} onClick={()=>toggleNotify("notify")}>Notificación {config.notify?"ON":"OFF"}</button><button className={config.sound?"on":""} onClick={()=>toggleNotify("sound")}>Sonido {config.sound?"ON":"OFF"}</button><button onClick={addRule}>＋ Regla</button></div></div>}
function GenerationSheet({product,original,latest,all}:{product:Product;original:VersionItem|null;latest:VersionItem|null;all:FactoryCapability[]}){const m=original?.metadata;return <section className="generation-sheet"><header><span>FICHA DE CONSTRUCCIÓN</span><h2>{product.name}</h2><p>{m?.request_summary||original?.change_summary||product.description||"Aún no hay una generación registrada."}</p></header><div className="sheet-grid"><Data k="Tipo" v={product.product_type}/><Data k="Estado" v={product.status}/><Data k="Versión" v={`v${product.current_version}`}/><Data k="Generada" v={fmt(m?.generated_at||original?.created_at)}/><Data k="Modelo" v={m?.model||"—"}/><Data k="Proveedor" v={m?.provider||"—"}/><Data k="Temperatura" v={m?.temperature!=null?String(m.temperature):"—"}/><Data k="Tokens" v={m?.usage?.total_tokens!=null?String(m.usage.total_tokens):"No reportados"}/><Data k="Skills" v={(m?.skills||[]).map(id=>skillName(id,all)).join(", ")||"—"}/><Data k="Style" v={m?.style?skillName(m.style,all):"—"}/><Data k="Referencias" v={String(m?.references?.length||0)}/><Data k="Assets" v={String(product.asset_count)}/></div>{m?.instruction&&<details><summary>Prompt original</summary><pre>{m.instruction}</pre></details>}{m?.compiled_prompt&&<details><summary>Prompt compilado</summary><pre>{m.compiled_prompt}</pre></details>}{latest&&latest.id!==original?.id&&<details><summary>Última edición IA</summary><p>{latest.change_summary}</p><pre>{latest.metadata?.instruction}</pre></details>}</section>}
function Versions({product,post}:{product:Product;post:(x:any)=>Promise<boolean>}){return <section className="versions-v2"><header><span>VERSIONADO</span><h2>Volver sin miedo.</h2></header>{product.history.map(v=><div className="history-row-v2" key={v.id}><div><b>v{v.version_number}{product.approved_version===v.version_number?" · APROBADA":""}</b><span>{v.change_summary||"Sin resumen"}</span><small>{v.metadata?.model||"manual"} · {fmt(v.metadata?.generated_at||v.created_at)}</small></div>{v.version_number!==product.current_version&&<button onClick={()=>post({action:"restore_version",product_id:product.id,version_number:v.version_number})}>Restaurar</button>}</div>)}</section>}
function PromptView({value}:{value:string}){return <div className="prompt-view"><p>Este es exactamente el contexto que recibe la IA antes del HTML actual.</p><pre>{value||"Presiona Prompt nuevamente para compilar."}</pre></div>}
function CodeView({value}:{value:string}){return <div className="prompt-view"><p>HTML actual de la construcción.</p><pre>{value||"Cargando…"}</pre></div>}
function PanelSection({title,add,children}:{title:string;add:()=>void;children:ReactNode}){return <section className="panel-section-v2"><header><b>{title}</b><button onClick={add}>＋</button></header>{children}</section>}
function Data({k,v}:{k:string;v:string}){return <div className="sheet-data"><small>{k}</small><b>{v}</b></div>}
function Row({a,b}:{a:string;b:string}){return <div className="row-v2"><b>{a}</b><span>{b}</span></div>}
function Hero({n,title,text}:{n:string;title:string;text:string}){return <header className="hero-v2"><span>{n}</span><div><h1>{title}</h1><p>{text}</p></div></header>}
function Empty({onCreate}:{onCreate:()=>void}){return <div className="empty-state-v2"><span>LINK FACTORY</span><h1>Crea el primer<br/>producto real.</h1><p>Luego activa skills, estilo, referencias y reglas antes de generar.</p><button onClick={onCreate}>Crear producto</button></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="modal-backdrop-v2" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><div className="modal-v2"><header><h3>{title}</h3><button onClick={close}>×</button></header>{children}</div></div>}
